# Generated by Django 4.2.7 on 2023-12-14 07:44

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("lists", "0005_alter_item_list"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="item",
            options={"ordering": ("id",)},
        ),
        migrations.AlterUniqueTogether(
            name="item",
            unique_together={("list", "text")},
        ),
    ]
